---
- name: Check if Helm is installed
  stat:
    path: /usr/local/bin/helm
  register: helm_installed
  when: addons_enabled and "{{addons.helm is defined}}"

- name: Install helm
  shell: curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > /root/get_helm.sh
  when: addons_enabled and "{{addons.ceph is defined}}" and helm_installed.stat.exists == False

- name: Set file properties
  file:
    path: /root/get_helm.sh
    mode: 0700
  when: addons_enabled and "{{addons.ceph is defined}}" and helm_installed.stat.exists == False

- name: Install helm
  shell: sh /root/get_helm.sh
  when: addons_enabled and "{{addons.ceph is defined}}" and helm_installed.stat.exists == False
