---
- name: Create directories for OpenStack Helm
  file:
    path: /opt/openstack-helm/repos/openstack-helm
    state: directory
  when: addons_enabled and "{{addons.osh is defined}}"

- name: Checkout OpenStack-Helm
  git:
    repo: https://github.com/att-comdev/openstack-helm.git
    dest: /opt/openstack-helm/repos/openstack-helm
    update: true
  when: addons_enabled and "{{addons.osh is defined}}"

- name: Check for Helm/Tiller
  shell: hyperkube kubectl get pods --namespace kube-system | grep tiller
  ignore_errors: true
  register: helm_running
  when: addons_enabled and "{{addons.osh is defined}}"

- name: Initialize Helm/Tiller
  shell: helm init --home /opt/openstack-helm/repos/openstack-helm/.helm
  environment:
    HELM_HOME: /opt/openstack-helm/repos/openstack-helm/.helm
  when: addons_enabled and "{{addons.osh is defined}}" and helm_running | failed

- name: Helm Serve
  shell: nohup helm serve --repo-path /opt/openstack-helm/repos/openstack-helm/.helm/repository/local &
  environment:
    HELM_HOME: /opt/openstack-helm/repos/openstack-helm/.helm
  args:
    chdir: /opt/openstack-helm/repos/openstack-helm/.helm
  when: addons_enabled and "{{addons.osh is defined}}" and helm_running | failed

- name: Add helm repositories
  shell: helm repo add local http://localhost:8879/charts --home /opt/openstack-helm/repos/openstack-helm/.helm
  args:
    chdir: /opt/openstack-helm/repos/openstack-helm/.helm
  when: addons_enabled and "{{addons.osh is defined}}" and helm_running | failed
