---
- name: Install Ceph
  apt:
    name: ceph-common
    state: present
  register: ceph_installed
  when: addons_enabled and "{{addons.ceph is defined}}"

- name: Create Ceph and OpenStack-Helm directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/var/lib/openstack-helm/ceph/osd"
    - "/var/lib/openstack-helm/ceph/ceph"
    - "/var/lib/openstack-helm/ceph/mon"
    - "/var/lib/nova/instances"
  when: addons_enabled and "{{addons.ceph is defined}}"

- name: Install Sigil for Ceph Secrets
  shell: curl -L https://github.com/gliderlabs/sigil/releases/download/v0.4.0/sigil_0.4.0_Linux_x86_64.tgz | tar -zxC /usr/local/bin
  when: addons_enabled and "{{addons.ceph is defined}}" and ceph_installed | changed

- name: Capture kubernetes version
  shell: kubelet --version | cut -d " " -f2
  register: kube_version
