- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - prep-bootstrap-cleanup

- hosts: bootstrap
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - prep-bootstrap

- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - prep-bootstrap-cni

- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - deploy-kubelet

- hosts: master
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - deploy-bootkube

- hosts: master
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - deploy-kubernetes-ha

#- hosts: master
#  remote_user: ubuntu
#  become: yes
#  become_method: sudo
#  roles:
#    - deploy-kubelet



#- hosts: master
#  remote_user: ubuntu
#  become: yes
#  become_method: sudo
#  roles:
#    - deploy-addons
