apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: kube-system
spec:
  selector:
    app: etcd
    etcd_cluster: kube-etcd
  clusterIP: 10.3.0.15
  ports:
  - name: client
    port: 2379
    protocol: TCP
