apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-calico-operator
  namespace: kube-system
  labels:
    k8s-app: etcd-calico-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: etcd-calico-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.2.4
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: kube-system
spec:
  selector:
    app: etcd
    etcd_cluster: calico-etcd
  clusterIP: 10.3.0.12
  ports:
  - name: client
    port: 6666
    protocol: TCP

