apiVersion: v1
kind: Service
metadata:
  name: calico-etcd-service
  namespace: kube-system
spec:
  selector:
    app: etcd
    etcd_cluster: calico-kube-etcd
  clusterIP: 10.3.0.25
  ports:
  - name: client
    port: 6666
    protocol: TCP
