---
- name: Setup bootkube.service
  when: bootstrap_enabled
  template:
    src: bootkube.service.j2
    dest: /etc/systemd/system/bootkube.service

- name: Run the bootkube service
  when: bootstrap_enabled
  systemd:
    name: bootkube
    state: started
    daemon_reload: yes

# Check every 15 seconds to make sure the Kubernetes API is responding
- action: shell kubectl --kubeconfig=/etc/kubernetes/kubeconfig get pods --all-namespaces | grep kube-apiserver
  when:
    - (bootstrap_enabled == 'true') and (inventory_hostname in groups['bootstrap'])
  register: kubeapi_output
  until: kubeapi_output.stdout.find("Running") != -1
  retries: 20
  delay: 15
