---
- name: bootstrap | check if bootstrap is needed
  raw: which python
  register: need_bootstrap
  ignore_errors: True

- name: bootstrap | install python 2.x
  raw: DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y python-minimal aptitude
  when: need_bootstrap | failed

- set_fact:
    ansible_python_interpreter: "/usr/bin/python"

#- name: upgrade the entire system in preparation for next steps
#  apt: upgrade=full update_cache=yes

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "docker.io"
    - "vim"
    - "ethtool"
    - "traceroute"
    - "git"
    - "build-essential"
    - "lldpd"
